app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    type:       rest
    resource:   AppBundle\Controller\PlaceController

logins:
    type:       rest
    resource:   AppBundle\Controller\LoginController