app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

login:
    type:       rest
    resource:   AppBundle\Controller\LoginController

register:
    type:       rest
    resource:   AppBundle\Controller\RegistrationController

auth-tokens:
    type:       rest
    resource:   AppBundle\Controller\AuthTokenController