app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    type:       rest
    resource:   AppBundle\Controller\PlaceController

login:
    type:       rest
    resource:   AppBundle\Controller\LoginController

register:
    type:       rest
    resource:   AppBundle\Controller\RegistrationController